### ISSUE TITLE
Build errors in CordovaPluginFileDemo

### ISSUE THREAD

**Issue by videophonegeek** [crosswalk-project/crosswalk-ios#24]
I encountered these when I opened the workspace and attempted to build:
![screen shot 2015-03-28 at 3 02 27 pm](https://cloud.githubusercontent.com/assets/191271/6879976/31fe6b10-d55c-11e4-8411-23703db82c3d.png)
![screen shot 2015-03-28 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/191271/6879977/320247bc-d55c-11e4-8eb9-52dcf188945f.png)
![screen shot 2015-03-28 at 3 03 33 pm](https://cloud.githubusercontent.com/assets/191271/6879978/3202f428-d55c-11e4-8555-0e846f4fa73f.png)

**Comment by jondong** [comment]
that's because my recent changes to the CDVViewController, I didn't check the integrity of this demo. I'll fix it very soon. Thanks for your finding.

**Comment by videophonegeek** [comment]
The "Sample" project was very helpful in learning the system.  The Plugin project I will try as soon as you make the fixes as I have some custom plugins. I would also like to see functionality for HTML5 W3C that are not implemented. If there is any interest, let me know in a PM or on the Intel XDK forum.

**Comment by jondong** [comment]
issue fixed. please have another try.
