### ISSUE TITLE
README screenshots

### ISSUE THREAD

**Issue by jondong** [crosswalk-project/crosswalk-ios#34]
This issue is used to host the uploaded images which are used in README.md. This is a trick to create an image url for your image files.

More detail please refer to: http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

**Comment by jondong** [comment]
![info_plist](https://cloud.githubusercontent.com/assets/700736/7226047/58728d94-e777-11e4-9fd4-8d23a24d981f.png)
![manifest_plist](https://cloud.githubusercontent.com/assets/700736/7226050/5e4027ae-e777-11e4-9897-de4441964d2c.png)

**Comment by jondong** [comment]
![manifest_plist1](https://cloud.githubusercontent.com/assets/700736/7226211/36a710c0-e779-11e4-9852-000d3bab8f57.png)
![manifest_plist2](https://cloud.githubusercontent.com/assets/700736/7226213/3ef59a9e-e779-11e4-822f-1ef6775723ad.png)

**Comment by zliang7** [comment]
So, can we close it?

**Comment by jondong** [comment]
sure, close it

**Comment by jondong** [comment]
![skitch 1](https://cloud.githubusercontent.com/assets/700736/8390269/c6422de4-1cbe-11e5-9dd5-3e7ea021d741.png)
![skitch 2](https://cloud.githubusercontent.com/assets/700736/8390271/c65d8bc0-1cbe-11e5-8ff5-2c537593403e.png)
![skitch 3](https://cloud.githubusercontent.com/assets/700736/8390270/c65d47a0-1cbe-11e5-8b8f-6dd2e48f612b.png)
![skitch 4](https://cloud.githubusercontent.com/assets/700736/8390272/c67221ca-1cbe-11e5-948d-e0f4e226f814.png)
![skitch 5](https://cloud.githubusercontent.com/assets/700736/8390273/c687a5a4-1cbe-11e5-9260-73848b9e023f.png)
![skitch 6](https://cloud.githubusercontent.com/assets/700736/8390276/c6d22d9a-1cbe-11e5-8aa4-56d15d98b928.png)
![skitch 7](https://cloud.githubusercontent.com/assets/700736/8390274/c6be5cca-1cbe-11e5-83c3-f7dd375bc1d4.png)
![skitch 8](https://cloud.githubusercontent.com/assets/700736/8390275/c6c92772-1cbe-11e5-92d1-53924098db46.png)
![skitch 9](https://cloud.githubusercontent.com/assets/700736/8390277/c7080352-1cbe-11e5-8fe7-81f788ed6861.png)
![skitch 10](https://cloud.githubusercontent.com/assets/700736/8390280/c76a93aa-1cbe-11e5-823a-bee32aa8f741.png)
![skitch 11](https://cloud.githubusercontent.com/assets/700736/8390278/c715238e-1cbe-11e5-9d25-eadcab37182b.png)
![skitch](https://cloud.githubusercontent.com/assets/700736/8390279/c749a460-1cbe-11e5-83b1-e5a51260e4a9.png)
